first commit
forseee/IBS_hometask2 pull request #1
Opened 2021-06-04 09:18 UTC by forseee

2021-06-04 12:52 UTC, Roman-Maksimov requested changes

2021-06-04 12:52 UTC, Roman-Maksimov commented on css/style.css
> +  max-width: 1448px;
По макету, ограничивать ширину не требуется. Пусть будет на всю

2021-06-04 12:52 UTC, Roman-Maksimov commented on css/style.css
> +  border-bottom: 2px solid #e97f03;
На бордер и на цвет иконки напрашивается анимация

2021-06-04 12:52 UTC, Roman-Maksimov commented on css/style.css
> +  padding: 50px 76px 50px 75px;
Когда будете натягивать верстку на данные, скорее всего вы не будете знать точный размер картинки. Тут требуется что-то более относительное

2021-06-04 12:52 UTC, Roman-Maksimov commented on css/style.css
> +}
у кнопки есть еще состояние :hover. По макету там добавляется тень и немного меняется цвет

2021-06-04 12:52 UTC, Roman-Maksimov commented on css/style.css
> +  padding: 50px 76px 50px 75px;
У картнки, по макету, еще есть рамка

2021-06-04 14:34 UTC, forseee commented on css/style.css
> +  padding: 50px 76px 50px 75px;
Я картинку вырезал без рамки , тк рамка потом мешает градиент сделать , я только там смог градиент накинуть красив о и на весь фон )

2021-06-04 14:39 UTC, forseee commented
Изменил

2021-06-04 15:37 UTC, Roman-Maksimov commented on css/style.css
> +  padding: 50px 76px 50px 75px;
Рамку можно сделать стилями, обычным `border`

2021-06-04 15:39 UTC, Roman-Maksimov requested changes

2021-06-04 15:39 UTC, Roman-Maksimov commented on css/style.css
> +  transition: all 0.3s;
transition лучше поместить в общий стиль, в противном случае браузер не гарантирует, что покаже анимацию при установке :hover, только при снятии

2021-06-04 15:40 UTC, Roman-Maksimov requested changes

2021-06-04 15:40 UTC, Roman-Maksimov commented on css/style.css
> +  transition: all 0.2s;
аналогично, transition лучше поместить в общий стиль

2021-06-04 16:05 UTC, forseee commented
Перенес , думал что он по другому маленько работает ,что  при нажатие только анимация работает а при отщелкивании нет

2021-06-06 09:41 UTC, forseee commented
Мне можно сливать или бордер добавить , просто зачем он нужен, белая рамка на белом фоне?

2021-06-08 17:12 UTC, forseee commented
Добавил  бордер

2021-06-08 17:54 UTC, Roman-Maksimov approved these changes

2021-06-14 07:18 UTC, merged